name: My First Pipeline

on:
  push:

jobs:

  hello:

    runs-on: ubuntu-latest

    steps:

     - name: Print message

        run: echo "Hello DevOps"

     - name: Starting

        run: echo "Starting pipeline"

     - name: Checking files

        run: echo "Checking files"

     - name: Finished

        run: echo "Pipeline finished"

